= Lucidworks API Documentation

This repository is for drafting and publishing Lucidworks API documentation. 

== Where to find the Swagger specs

The script at `scripts/fusionSpecsCollector.sh` should fetch the latest specs.
You can modify it to point at any Fusion build.
You can find the fetched specs per Fusion version in `originals/`.

The script also pretty-prints the JSON files with `jq`.
By formatting all of the files the same way with the same tool, we can get better diffs.
You can also pretty-print a directory of JSON files with `scripts/pretty-print-json.sh`.

Note that the fetched specs are not accurate.
Therefore, we only use them to check for changes so we can manually update the corrected specs as explained in the next section.

== Update the existing API documentation

=== Maintenance releases

With every Fusion release, the original configuration spec provided in the software is fetch and saved in the `originals` directory. 
The previous original file is overwritten by the new original file, and git comparisons are studied to find changes to the APIs. 
The configuration specs in `reference` do not receive the software-sourced spec. 
If changes were detected in the git comparison, the configuration spec is manually updated. 

=== Rapid or LTS releases

A similar process is followed for rapid and LTS releases. However, when a new original file is captured, it does not overwrite a previous version, as no previous version exists. The git comparison is performed between the rapid/LTS configuration spec and the most recent maintenance configuration spec. 
The configuration spec in `reference` is manually updated.


== Swagger API style guidelines (proposed)

Some API style guidelines are specified in https://developers.google.com/style/api-reference-comments.
This section discusses some additional details not included there.

=== The "title" field

Each Swagger file as a whole has one "title".
Its format should be: "Fusion <service> APIs", as in "Fusion Query APIs".

=== The "summary" field

Every method for every endpoint must have a `summary` field.
Its value should be as concise as possible, because this is the field that is rendered as a link in the narrow left nav.
The rendered link does not wrap; it is truncated if it is longer than the width of the nav pane.

Don't use terminal punctuation (.) in summaries.

For each type of operation, use consistent phrasing:

* `GET` status - "Get <service> service status", as in "Get query service status".
* `GET` all - "List all <objects>", such as "List all users".
Sometimes "List matching <objects>" or similar.
* `GET` one - "Get an <object>", as in "Get a user".
Sometimes "Get <object> status", "Get <object> features", or similar depending on functionality.
* `POST` - "Create an <object>", as in "Create a user".
* `PUT` - "Update an <object>", as in "Update a user".
This method can use other verbs, such as "Reload an <object>".
* `DELETE` - "Delete an <object>", as in "Delete a user".
* `HEAD` - "Get <object> metadata", as in "Get user metadata".

Be specific about the type of object being operated upon.
Avoid using generic nouns like "object" or "entity".
Eliminate duplicate summaries by making each one specific enough to be unique.

=== The "description" field

Every method for every endpoint must have a `description` field in addition to the `summary` field.
Every object model and parameter should also have a `description` field, unless the item is too generic to meaningfully describe.
In addition, each Swagger file as a whole has a `description`.

Unlike the `summary` field, the `description` can be as detailed as necessary and can contain markdown formatting, escaped line breaks, and so on.  It's also okay to be brief if there is not much to describe.

One notable exception to the Google Developer Style Guide is that we use the imperative case for the first sentence of descriptions, in order to avoid writing an incomplete sentence.
That is, begin a description with a sentence like, "Get the list of existing collections" and not like "Gets the list of existing collections."

=== The "example" field

This field is optional and can be added to parameter definitions as needed to clarify how to format a value.
For example, the value of the `context` parameter can be clarified with `"example": "app:my-fusion-app"` so the user can see how the prefix and the app name are combined.

=== The "externalDocs" field

This is another optional field.
It can be useful for pointing the user to a more detailed document about how to use an endpoint.

NOTE: I think this field isn't even rendered on our site.  Is this a stoplight setting we can change?

Use this field sparingly to avoid creating link maintenance work.
It can be useful for pointing to Solr documentation, such as reference docs about search handlers or other details that are too verbose for Swagger docs.


== Build locally using unpublished/draft API docs

By default, a local build in the `fusion-docs-site` repo uses the `main` branch of the `api-docs` repo.

.To use another branch of the `api-docs` repo:
. In the `fusion-docs-site` repo, edit this line in `package.json` by replacing `main` with your branch name:
+
[source,json]
----
    "api-docs": "git+https://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@github.com/lucidworks/api-docs.git#main",
----
. Run `yarn install` to pick up the change.
. Run `yarn fresh` to build the site.
+
NOTE: Repeat these last two steps each time you push new changes to the branch in `api-docs`.  This pulls your latest changes into your site build.

Be sure to undo the change to `package.json` before committing.


== How to investigate missing/wrong endpoint documentation

Here's how to discover the correct information about the real endpoints.

.Spy on the Fusion UI while it accesses the APIs
. Log in to the Fusion UI on Chrome.
. Open Chrome's *Developer Tools* and go to the *Network* tab.
. Click around the Fusion UI.
. Observe the API *Request URLs* displayed in the *Network* tab.

.Test the endpoints in Postman
. Import your swagger file into Postman.
. Generate tests for each endpoint and method.
. Update the swagger based on test requests and responses.
