---
swagger: "2.0"
info:
  version: "4.0.0-dev59"
  title: "Fusion Service synonyms"
basePath: "/api/apollo"
tags:
- name: "synonyms"
schemes:
- "http"
paths:
  /synonyms/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
  /synonyms/{collection}:
    get:
      operationId: "exportResource"
      produces:
      - "application/octet-stream"
      parameters:
      - name: "collection"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "string"
              format: "byte"
          headers: {}
    put:
      operationId: "importResource"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "collection"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/FormDataMultiPart"
      responses:
        default:
          description: "successful operation"
definitions:
  MessageBodyWorkers:
    type: "object"
  BodyPart:
    type: "object"
    properties:
      contentDisposition:
        $ref: "#/definitions/ContentDisposition"
      entity:
        type: "object"
      headers:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            type: "string"
      mediaType:
        $ref: "#/definitions/MediaType"
      messageBodyWorkers:
        $ref: "#/definitions/MessageBodyWorkers"
      parent:
        $ref: "#/definitions/MultiPart"
      providers:
        $ref: "#/definitions/Providers"
      parameterizedHeaders:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            $ref: "#/definitions/ParameterizedHeader"
  ParameterizedHeader:
    type: "object"
    properties:
      value:
        type: "string"
      parameters:
        type: "object"
        additionalProperties:
          type: "string"
  Providers:
    type: "object"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
  MultiPart:
    type: "object"
    properties:
      contentDisposition:
        $ref: "#/definitions/ContentDisposition"
      entity:
        type: "object"
      headers:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            type: "string"
      mediaType:
        $ref: "#/definitions/MediaType"
      messageBodyWorkers:
        $ref: "#/definitions/MessageBodyWorkers"
      parent:
        $ref: "#/definitions/MultiPart"
      providers:
        $ref: "#/definitions/Providers"
      bodyParts:
        type: "array"
        items:
          $ref: "#/definitions/BodyPart"
      parameterizedHeaders:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            $ref: "#/definitions/ParameterizedHeader"
  ContentDisposition:
    type: "object"
    properties:
      type:
        type: "string"
      parameters:
        type: "object"
        additionalProperties:
          type: "string"
      fileName:
        type: "string"
      creationDate:
        type: "string"
        format: "date-time"
      modificationDate:
        type: "string"
        format: "date-time"
      readDate:
        type: "string"
        format: "date-time"
      size:
        type: "integer"
        format: "int64"
  FormDataBodyPart:
    type: "object"
    properties:
      contentDisposition:
        $ref: "#/definitions/ContentDisposition"
      entity:
        type: "object"
      headers:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            type: "string"
      mediaType:
        $ref: "#/definitions/MediaType"
      messageBodyWorkers:
        $ref: "#/definitions/MessageBodyWorkers"
      parent:
        $ref: "#/definitions/MultiPart"
      providers:
        $ref: "#/definitions/Providers"
      name:
        type: "string"
      value:
        type: "string"
      formDataContentDisposition:
        $ref: "#/definitions/FormDataContentDisposition"
      simple:
        type: "boolean"
        default: false
      parameterizedHeaders:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            $ref: "#/definitions/ParameterizedHeader"
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  FormDataMultiPart:
    type: "object"
    properties:
      contentDisposition:
        $ref: "#/definitions/ContentDisposition"
      entity:
        type: "object"
      headers:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            type: "string"
      mediaType:
        $ref: "#/definitions/MediaType"
      messageBodyWorkers:
        $ref: "#/definitions/MessageBodyWorkers"
      parent:
        $ref: "#/definitions/MultiPart"
      providers:
        $ref: "#/definitions/Providers"
      bodyParts:
        type: "array"
        items:
          $ref: "#/definitions/BodyPart"
      fields:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            $ref: "#/definitions/FormDataBodyPart"
      parameterizedHeaders:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            $ref: "#/definitions/ParameterizedHeader"
  MediaType:
    type: "object"
    properties:
      type:
        type: "string"
      subtype:
        type: "string"
      parameters:
        type: "object"
        additionalProperties:
          type: "string"
      wildcardType:
        type: "boolean"
        default: false
      wildcardSubtype:
        type: "boolean"
        default: false
  Synonym:
    type: "object"
    properties:
      match:
        type: "array"
        items:
          type: "string"
      replace:
        type: "array"
        items:
          type: "string"
  FormDataContentDisposition:
    type: "object"
    properties:
      type:
        type: "string"
      parameters:
        type: "object"
        additionalProperties:
          type: "string"
      fileName:
        type: "string"
      creationDate:
        type: "string"
        format: "date-time"
      modificationDate:
        type: "string"
        format: "date-time"
      readDate:
        type: "string"
        format: "date-time"
      size:
        type: "integer"
        format: "int64"
      name:
        type: "string"
