---
swagger: "2.0"
info:
  version: "4.0.2-SNAPSHOT"
  title: "Fusion Service zk-import-export"
basePath: "/api/apollo"
tags:
- name: "zk-import-export"
schemes:
- "http"
paths:
  /zk/export/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
  /zk/export/{path}:
    get:
      summary: "Download information from ZooKeeper"
      description: ""
      operationId: "getNodeInfo"
      produces:
      - "application/json"
      parameters:
      - name: "path"
        in: "query"
        description: "NEEDS DEVELOPER REVIEW"
        required: false
        type: "string"
        pattern: ".*"
      - name: "recursive"
        in: "query"
        description: "NEEDS DEVELOPER REVIEW"
        required: false
        type: "boolean"
        default: true
      - name: "excludePaths"
        in: "query"
        description: "NEEDS DEVELOPER REVIEW"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      - name: "includePaths"
        in: "query"
        description: "NEEDS DEVELOPER REVIEW"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      - name: "encodeValues"
        in: "query"
        description: "NEEDS DEVELOPER REVIEW"
        required: false
        type: "string"
        default: "base64"
      - name: "ephemeral"
        in: "query"
        description: "NEEDS DEVELOPER REVIEW"
        required: false
        type: "boolean"
        default: false
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ZNodeDump"
definitions:
  ZNodeDump:
    type: "object"
    properties:
      znodeExportRequest:
        $ref: "#/definitions/ZNodeDumpRequest"
      getzNode:
        $ref: "#/definitions/ZNode"
  ZNode:
    type: "object"
    properties:
      path:
        type: "string"
      children:
        type: "array"
        items:
          $ref: "#/definitions/ZNode"
      data:
        type: "string"
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  Params:
    type: "object"
    properties:
      zkHost:
        type: "string"
      path:
        type: "string"
      encodeValues:
        type: "string"
      recursive:
        type: "boolean"
        default: false
      includePaths:
        type: "array"
        items:
          type: "string"
      excludePaths:
        type: "array"
        items:
          type: "string"
      ephemeral:
        type: "boolean"
        default: false
  ZNodeDumpRequest:
    type: "object"
    properties:
      timestamp:
        type: "string"
        format: "date-time"
      params:
        $ref: "#/definitions/Params"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
