---
swagger: "2.0"
info:
  version: "4.0.2-SNAPSHOT"
  title: "Fusion Service solr"
basePath: "/api/apollo"
tags:
- name: "solr"
schemes:
- "http"
paths:
  /solr:
    get:
      operationId: "ok"
      produces:
      - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
  /solr/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
  /solr/{collection}/{path}:
    get:
      operationId: "proxyRequestToSolr"
      parameters:
      - name: "collection"
        in: "path"
        required: true
        type: "string"
      - name: "path"
        in: "path"
        required: true
        type: "string"
        pattern: ".*"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/InputStream"
      responses:
        default:
          description: "successful operation"
    post:
      operationId: "proxyPostRequestToSolr"
      parameters:
      - name: "collection"
        in: "path"
        required: true
        type: "string"
      - name: "path"
        in: "path"
        required: true
        type: "string"
        pattern: ".*"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/InputStream"
      responses:
        default:
          description: "successful operation"
    put:
      operationId: "proxyPutRequestToSolr"
      parameters:
      - name: "collection"
        in: "path"
        required: true
        type: "string"
      - name: "path"
        in: "path"
        required: true
        type: "string"
        pattern: ".*"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/InputStream"
      responses:
        default:
          description: "successful operation"
    delete:
      operationId: "proxyDeleteRequestToSolr"
      parameters:
      - name: "collection"
        in: "path"
        required: true
        type: "string"
      - name: "path"
        in: "path"
        required: true
        type: "string"
        pattern: ".*"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/InputStream"
      responses:
        default:
          description: "successful operation"
definitions:
  PushbackInputStream:
    type: "object"
  InputStream:
    type: "object"
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  Builder:
    type: "object"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
