---
swagger: "2.0"
info:
  version: "4.0.2-SNAPSHOT"
  title: "Fusion Service usage"
basePath: "/api/apollo"
tags:
- name: "usage"
schemes:
- "http"
paths:
  /usage:
    get:
      summary: "Get system usage statistics"
      description: ""
      operationId: "getUsageMetrics"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "local"
        in: "query"
        description: "The cluster ID"
        required: false
        type: "boolean"
        default: false
      - name: "includeServerInfo"
        in: "query"
        description: "The cluster ID"
        required: false
        type: "boolean"
        default: true
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/MetricValue"
  /usage/counters:
    get:
      summary: "List all available usage counters"
      description: ""
      operationId: "getCounters"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "string"
  /usage/counters/{key}:
    get:
      summary: "Get a specific counter"
      description: ""
      operationId: "getCounter"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "key"
        in: "path"
        description: "The counter key"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "integer"
            format: "int64"
    put:
      summary: "Update a counter"
      description: ""
      operationId: "incrementCounter"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "key"
        in: "path"
        description: "The counter key"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "The counter value"
        required: false
        schema:
          type: "object"
      responses:
        default:
          description: "successful operation"
  /usage/id:
    get:
      summary: "Get the UUID of the system"
      description: ""
      operationId: "getUUID"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /usage/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
definitions:
  MetricValue:
    type: "object"
    properties:
      type:
        type: "string"
        enum:
        - "GAUGE"
        - "RATE"
      name:
        type: "string"
      value:
        type: "object"
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
