---
swagger: "2.0"
info:
  version: "4.0.0-dev88"
  title: "Fusion Service dynamicSchema"
basePath: "/api/apollo"
tags:
- name: "dynamicSchema"
schemes:
- "http"
paths:
  /dynamicSchema/_changed:
    post:
      operationId: "changeCallback"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Feature"
      responses:
        default:
          description: "successful operation"
  /dynamicSchema/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
definitions:
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  Feature:
    type: "object"
    properties:
      name:
        type: "string"
      collectionId:
        type: "string"
      params:
        type: "object"
        additionalProperties:
          type: "object"
      enabled:
        type: "boolean"
        default: false
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
