---
swagger: "2.0"
info:
  version: "4.0.2-SNAPSHOT"
  title: "Fusion Service history"
basePath: "/api/apollo"
tags:
- name: "history"
schemes:
- "http"
paths:
  /history:
    get:
      summary: "Return a list of services"
      description: ""
      operationId: "listAllServices"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "string"
    delete:
      summary: "Clear the histories for all services"
      description: ""
      operationId: "clearAllServiceHistory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
  /history/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
  /history/{service}:
    get:
      summary: "Return information about a service"
      description: ""
      operationId: "getServiceHistory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "service"
        in: "path"
        description: "The name of a service"
        required: true
        type: "string"
      - name: "timeRange"
        in: "query"
        description: "NEEDS DEVELOPER REVIEW"
        required: false
        type: "string"
      - name: "maxLength"
        in: "query"
        description: "NEEDS DEVELOPER REVIEW"
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/History"
    put:
      summary: "For internal use by the system"
      description: ""
      operationId: "addServiceHistory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "service"
        in: "path"
        description: "The name of a service"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "JSON-formatted configuration values"
        required: false
        schema:
          $ref: "#/definitions/HistoryEvent"
      responses:
        default:
          description: "successful operation"
    delete:
      summary: "Delete all history for a specified service"
      description: ""
      operationId: "clearServiceHistory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "service"
        in: "path"
        description: "The name of a service"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
  /history/{service}/items:
    get:
      summary: "Return all items in a service's history"
      description: ""
      operationId: "listAllItems"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "service"
        in: "path"
        description: "The name of a service"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "string"
    delete:
      summary: "Clear all items from a service's history"
      description: ""
      operationId: "clearAllItemHistory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "service"
        in: "path"
        description: "The name of a service"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
  /history/{service}/items/{item}:
    get:
      summary: "Return a specific item in a service's history"
      description: ""
      operationId: "getItemHistory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "service"
        in: "path"
        description: "The name of a service"
        required: true
        type: "string"
      - name: "item"
        in: "path"
        description: "The name of a history item"
        required: true
        type: "string"
      - name: "timeRange"
        in: "query"
        description: "NEEDS DEVELOPER REVIEW"
        required: false
        type: "string"
      - name: "maxLength"
        in: "query"
        description: "NEEDS DEVELOPER REVIEW"
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/History"
    put:
      summary: "Add an item to a service's history"
      description: ""
      operationId: "addItemHistory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "service"
        in: "path"
        description: "The name of a service"
        required: true
        type: "string"
      - name: "item"
        in: "path"
        description: "The name of a history item"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "JSON-formatted history items"
        required: false
        schema:
          $ref: "#/definitions/HistoryEvent"
      responses:
        default:
          description: "successful operation"
    delete:
      summary: "Clear a specific item from a service's history"
      description: ""
      operationId: "clearItemHistory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "service"
        in: "path"
        description: "The name of a service"
        required: true
        type: "string"
      - name: "item"
        in: "path"
        description: "The name of a history item"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
definitions:
  ErrorType:
    type: "object"
    properties:
      component:
        type: "string"
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  StatusType:
    type: "object"
    properties:
      reasonPhrase:
        type: "string"
      family:
        type: "string"
        enum:
        - "INFORMATIONAL"
        - "SUCCESSFUL"
        - "REDIRECTION"
        - "CLIENT_ERROR"
        - "SERVER_ERROR"
        - "OTHER"
      statusCode:
        type: "integer"
        format: "int32"
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  StackTraceElement:
    type: "object"
    properties:
      methodName:
        type: "string"
      fileName:
        type: "string"
      lineNumber:
        type: "integer"
        format: "int32"
      className:
        type: "string"
      nativeMethod:
        type: "boolean"
        default: false
  Throwable:
    type: "object"
    properties:
      cause:
        $ref: "#/definitions/Throwable"
      stackTrace:
        type: "array"
        items:
          $ref: "#/definitions/StackTraceElement"
      message:
        type: "string"
      localizedMessage:
        type: "string"
      suppressed:
        type: "array"
        items:
          $ref: "#/definitions/Throwable"
  HistoryEvent:
    type: "object"
    properties:
      start:
        type: "string"
        format: "date-time"
      end:
        type: "string"
        format: "date-time"
      type:
        type: "string"
      source:
        type: "string"
      status:
        type: "string"
      details:
        type: "object"
        additionalProperties:
          type: "object"
      error:
        $ref: "#/definitions/RESTError"
  History:
    type: "object"
    properties:
      events:
        type: "array"
        items:
          $ref: "#/definitions/HistoryEvent"
  RESTError:
    type: "object"
    properties:
      cause:
        $ref: "#/definitions/Throwable"
      stackTrace:
        type: "array"
        items:
          $ref: "#/definitions/StackTraceElement"
      errorType:
        $ref: "#/definitions/ErrorType"
      recommendedHttpStatus:
        $ref: "#/definitions/StatusType"
      httpStatus:
        type: "integer"
        format: "int32"
      headers:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            type: "object"
      message:
        type: "string"
      error:
        type: "string"
      errorMessage:
        type: "string"
      httpStatusMessage:
        type: "string"
      exceptionClass:
        type: "string"
      localizedMessage:
        type: "string"
      suppressed:
        type: "array"
        items:
          $ref: "#/definitions/Throwable"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
