---
swagger: "2.0"
info:
  version: "4.0.2-SNAPSHOT"
  title: "Fusion Service taxonomy"
basePath: "/api/apollo"
tags:
- name: "taxonomy"
schemes:
- "http"
paths:
  /collections/{collection}/taxonomy:
    get:
      summary: "Retrieve the root categories in a taxonomy"
      description: ""
      operationId: "getRootCategories"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "collection"
        in: "path"
        description: "The name of a collection"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Category"
    post:
      summary: "Create one or more new top-level categories in a taxonomy"
      description: ""
      operationId: "createRootCategories"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "collection"
        in: "path"
        description: "The name of a collection"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "JSON-formatted list of categories"
        required: false
        schema:
          type: "array"
          items:
            $ref: "#/definitions/Category"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Category"
    put:
      summary: "Replace a taxonomy"
      description: ""
      operationId: "replaceTaxonomy"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "collection"
        in: "path"
        description: "The name of a collection"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "JSON-formatted list of categories"
        required: false
        schema:
          type: "array"
          items:
            $ref: "#/definitions/Category"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Category"
    delete:
      summary: "Delete a taxonomy"
      description: ""
      operationId: "deleteTaxonomy"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "collection"
        in: "path"
        description: "The name of a collection"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
  /collections/{collection}/taxonomy/_schema:
    get:
      summary: "Get the schema for this service"
      description: ""
      operationId: "getSchema"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "collection"
        in: "path"
        description: "The name of a collection"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ObjectType"
  /collections/{collection}/taxonomy/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
  /collections/{collection}/taxonomy/{category}:
    get:
      summary: "Retrieve a category"
      description: ""
      operationId: "getCategory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "collection"
        in: "path"
        description: "The name of a collection"
        required: true
        type: "string"
      - name: "category"
        in: "path"
        description: "The name of a category"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Category"
    put:
      summary: "Update a category"
      description: ""
      operationId: "updateCategory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "collection"
        in: "path"
        description: "The name of a collection"
        required: true
        type: "string"
      - name: "category"
        in: "path"
        description: "The name of a category"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "JSON-formatted category configuration"
        required: false
        schema:
          $ref: "#/definitions/Category"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Category"
    delete:
      summary: "Delete a category"
      description: ""
      operationId: "deleteCategory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "collection"
        in: "path"
        description: "The name of a collection"
        required: true
        type: "string"
      - name: "category"
        in: "path"
        description: "The name of a category"
        required: true
        type: "string"
      - name: "version"
        in: "query"
        description: "A string corresponding to the integer value of some system clock\
          \ in milliseconds"
        required: false
        type: "string"
      responses:
        default:
          description: "successful operation"
  /collections/{collection}/taxonomy/{category}/children/{child}:
    put:
      summary: "Update a category's child object"
      description: ""
      operationId: "addChildCategory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "collection"
        in: "path"
        description: "The name of a collection"
        required: true
        type: "string"
      - name: "category"
        in: "path"
        description: "The name of a category"
        required: true
        type: "string"
      - name: "child"
        in: "path"
        description: "The name of a category object"
        required: true
        type: "string"
      - name: "version"
        in: "body"
        description: "The category's latest version, for optimistic concurrency control"
        required: false
        type: "string"
      - in: "body"
        name: "body"
        description: "JSON-formatted category object configuration"
        required: false
        schema:
          $ref: "#/definitions/Category"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Category"
    delete:
      summary: "Delete a category's child object"
      description: ""
      operationId: "removeChildCategory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "collection"
        in: "path"
        description: "The name of a collection"
        required: true
        type: "string"
      - name: "category"
        in: "path"
        description: "The name of a category"
        required: true
        type: "string"
      - name: "child"
        in: "path"
        description: "The name of a category object"
        required: true
        type: "string"
      - name: "version"
        in: "body"
        description: "The category's latest version, for optimistic concurrency control"
        required: false
        type: "string"
      responses:
        default:
          description: "successful operation"
definitions:
  ObjectType:
    type: "object"
    properties:
      title:
        type: "string"
      description:
        type: "string"
      category:
        type: "string"
      categoryPriority:
        type: "integer"
        format: "int32"
      allowedValues:
        type: "array"
        uniqueItems: true
        items:
          type: "object"
      hints:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      defaultValue:
        type: "object"
      accessibleProperty:
        $ref: "#/definitions/AccessibleProperty"
      oneOf:
        type: "array"
        items:
          $ref: "#/definitions/AnyTypeObjectObject"
      maxProperties:
        type: "integer"
        format: "int32"
      minProperties:
        type: "integer"
        format: "int32"
      required:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      properties:
        type: "object"
        additionalProperties:
          $ref: "#/definitions/AnyType"
      propertyGroups:
        type: "array"
        items:
          $ref: "#/definitions/PropertyGroup"
      definitions:
        type: "object"
        additionalProperties:
          $ref: "#/definitions/AnyType"
      type:
        type: "string"
        enum:
        - "String"
        - "Number"
        - "Integer"
        - "Boolean"
        - "Object"
        - "Array"
        - "Null"
        - "Ref"
      additionalProperties:
        type: "object"
  Type:
    type: "object"
    properties:
      typeName:
        type: "string"
  Category:
    type: "object"
    properties:
      id:
        type: "string"
      label:
        type: "string"
      version:
        type: "string"
      parameters:
        type: "array"
        items:
          $ref: "#/definitions/KeyValue"
      children:
        type: "array"
        items:
          $ref: "#/definitions/Category"
      parents:
        type: "array"
        items:
          type: "string"
  KeyValue:
    type: "object"
    properties:
      key:
        type: "string"
      value:
        type: "string"
  PropertyGroup:
    type: "object"
    properties:
      label:
        type: "string"
      properties:
        type: "array"
        items:
          type: "string"
  AccessibleProperty:
    type: "object"
    properties:
      name:
        type: "string"
      required:
        type: "boolean"
        default: false
      genericType:
        $ref: "#/definitions/Type"
      accessibleObject:
        $ref: "#/definitions/AccessibleObject"
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  AccessibleObject:
    type: "object"
    properties:
      annotations:
        type: "array"
        items:
          $ref: "#/definitions/Annotation"
      declaredAnnotations:
        type: "array"
        items:
          $ref: "#/definitions/Annotation"
      accessible:
        type: "boolean"
        default: false
  AnyType:
    type: "object"
    properties:
      title:
        type: "string"
      description:
        type: "string"
      category:
        type: "string"
      categoryPriority:
        type: "integer"
        format: "int32"
      allowedValues:
        type: "array"
        uniqueItems: true
        items:
          type: "object"
      hints:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      defaultValue:
        type: "object"
      accessibleProperty:
        $ref: "#/definitions/AccessibleProperty"
      oneOf:
        type: "array"
        items:
          $ref: "#/definitions/AnyTypeObjectObject"
      type:
        type: "string"
        enum:
        - "String"
        - "Number"
        - "Integer"
        - "Boolean"
        - "Object"
        - "Array"
        - "Null"
        - "Ref"
  Annotation:
    type: "object"
  AnyTypeObjectObject:
    type: "object"
    properties:
      title:
        type: "string"
      description:
        type: "string"
      category:
        type: "string"
      categoryPriority:
        type: "integer"
        format: "int32"
      allowedValues:
        type: "array"
        uniqueItems: true
        items:
          type: "object"
      hints:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      defaultValue:
        type: "object"
      accessibleProperty:
        $ref: "#/definitions/AccessibleProperty"
      oneOf:
        type: "array"
        items:
          $ref: "#/definitions/AnyTypeObjectObject"
      type:
        type: "string"
        enum:
        - "String"
        - "Number"
        - "Integer"
        - "Boolean"
        - "Object"
        - "Array"
        - "Null"
        - "Ref"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
