---
swagger: "2.0"
info:
  version: "4.1.3"
  title: "Fusion Service registration"
basePath: "/api/apollo"
tags:
- name: "registration"
schemes:
- "http"
paths:
  /registration:
    get:
      operationId: "get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/RegistrationData"
          headers: {}
    put:
      operationId: "update"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/RegistrationData"
      responses:
        default:
          description: "successful operation"
  /registration/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
definitions:
  RegistrationData:
    type: "object"
    properties:
      properties:
        type: "object"
        additionalProperties:
          type: "object"
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  CuratorComponent:
    type: "object"
    properties:
      zkConnect:
        type: "string"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
