---
swagger: "2.0"
info:
  version: "4.0.2-SNAPSHOT"
  title: "Fusion Service parser-templates"
basePath: "/api/apollo"
tags:
- name: "parser-templates"
schemes:
- "http"
paths:
  /templates/parsers:
    get:
      operationId: "getTemplates"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/IterableParserConfig"
          headers: {}
  /templates/parsers/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
  /templates/parsers/{templateId}:
    get:
      operationId: "getTemplate"
      produces:
      - "application/json"
      parameters:
      - name: "templateId"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ParserConfig"
          headers: {}
definitions:
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  ParserStageConfig:
    type: "object"
    properties:
      id:
        type: "string"
      label:
        type: "string"
      enabled:
        type: "boolean"
        default: false
      mediaTypes:
        type: "array"
        items:
          type: "string"
      pathPatterns:
        type: "array"
        items:
          $ref: "#/definitions/SyntaxAndPattern"
      inheritMediaTypes:
        type: "boolean"
        default: false
      errorHandling:
        type: "string"
        enum:
        - "IGNORE"
        - "LOG"
        - "FAIL"
        - "MARK"
      outputFieldPrefix:
        type: "string"
      type:
        type: "string"
  ParserConfig:
    type: "object"
    properties:
      id:
        type: "string"
      idField:
        type: "string"
      enableMediaTypeDetection:
        type: "boolean"
        default: false
      maxParserDepth:
        type: "integer"
        format: "int32"
      parserStages:
        type: "array"
        items:
          $ref: "#/definitions/ParserStageConfig"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      hidden:
        type: "boolean"
        default: false
  SyntaxAndPattern:
    type: "object"
    properties:
      syntax:
        type: "string"
        enum:
        - "GLOB"
        - "REGEX"
      pattern:
        type: "string"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
