---
swagger: "2.0"
info:
  version: "4.0.2-SNAPSHOT"
  title: "Fusion Service jobs"
basePath: "/api/apollo"
tags:
- name: "jobs"
schemes:
- "http"
paths:
  /jobs:
    get:
      summary: "List all jobs"
      description: ""
      operationId: "listJobs"
      parameters:
      - name: "status"
        in: "query"
        description: "Filter jobs by status, one of: `ready`, `running`, `success`,\
          \ `aborted`, or `failed`"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      - name: "enabled"
        in: "query"
        description: "Filter jobs by whether they are enabled (`true`) or disabled\
          \ (`false`)"
        required: false
        type: "string"
      - name: "type"
        in: "query"
        description: "Filter jobs by type, one of: `task`, `spark`, or `datasource`"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/JobView"
  /jobs/_schema:
    get:
      operationId: "getJobConfigSchema"
      produces:
      - "application/schema+json; qs=1.0"
      - "application/json; qs=0.9"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ObjectType"
          headers: {}
  /jobs/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
  /jobs/{resource}:
    get:
      summary: "Get the status and configuration for the specified job"
      description: ""
      operationId: "getJob"
      parameters:
      - name: "resource"
        in: "path"
        description: "The job ID"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/JobView"
  /jobs/{resource}/actions:
    post:
      summary: "Start, pause, or abort the specified job"
      description: ""
      operationId: "controlJob"
      parameters:
      - name: "resource"
        in: "path"
        description: "The job ID"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "One of: `start` or `abort`"
        required: false
        schema:
          $ref: "#/definitions/JobActionRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/JobActionResponse"
  /jobs/{resource}/history:
    get:
      summary: "Get the run history for the specified job"
      description: ""
      operationId: "listJobHistory"
      parameters:
      - name: "resource"
        in: "path"
        description: "The job ID"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/JobRunView"
  /jobs/{resource}/schedule:
    get:
      summary: "Get the schedule for the specified job"
      description: ""
      operationId: "getJobConfig"
      parameters:
      - name: "resource"
        in: "path"
        description: "The job ID"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/JobConfig"
    put:
      summary: "Configure the schedule for the specified job"
      description: ""
      operationId: "setJobConfig"
      parameters:
      - name: "resource"
        in: "path"
        description: "The job ID"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "JSON-formatted configuration values"
        required: false
        schema:
          $ref: "#/definitions/JobConfig"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/JobConfig"
    delete:
      summary: "Reset the schedule for the specified job"
      description: ""
      operationId: "resetJobConfig"
      parameters:
      - name: "resource"
        in: "path"
        description: "The job ID"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
definitions:
  PropertyGroup:
    type: "object"
    properties:
      label:
        type: "string"
      properties:
        type: "array"
        items:
          type: "string"
  JobActionResponse:
    type: "object"
    properties:
      resource:
        type: "string"
      action:
        type: "string"
        enum:
        - "START"
        - "PAUSE"
        - "ABORT"
      accepted:
        type: "boolean"
        default: false
      message:
        type: "string"
  JobRunView:
    type: "object"
    properties:
      resource:
        $ref: "#/definitions/FusionResource"
      startTime:
        type: "string"
        format: "date-time"
      endTime:
        type: "string"
        format: "date-time"
      status:
        type: "string"
      extra:
        type: "object"
        additionalProperties:
          type: "string"
      startedBy:
        type: "string"
  JobView:
    type: "object"
    properties:
      resource:
        $ref: "#/definitions/FusionResource"
      enabled:
        type: "boolean"
        default: false
      startedBy:
        type: "string"
      status:
        type: "string"
      extra:
        type: "object"
        additionalProperties:
          type: "string"
      lastStartTime:
        type: "string"
        format: "date-time"
      lastEndTime:
        type: "string"
        format: "date-time"
      nextStartTime:
        type: "string"
        format: "date-time"
  JobConfig:
    type: "object"
    properties:
      jobResource:
        $ref: "#/definitions/FusionResource"
      enabled:
        type: "boolean"
        default: false
      triggers:
        type: "array"
        items:
          $ref: "#/definitions/JobTriggerConfig"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      default:
        type: "boolean"
        default: false
  Annotation:
    type: "object"
  JobTriggerConfig:
    type: "object"
    properties:
      enabled:
        type: "boolean"
        default: false
      type:
        type: "string"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
  ObjectType:
    type: "object"
    properties:
      title:
        type: "string"
      description:
        type: "string"
      category:
        type: "string"
      categoryPriority:
        type: "integer"
        format: "int32"
      allowedValues:
        type: "array"
        uniqueItems: true
        items:
          type: "object"
      hints:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      defaultValue:
        type: "object"
      accessibleProperty:
        $ref: "#/definitions/AccessibleProperty"
      oneOf:
        type: "array"
        items:
          $ref: "#/definitions/AnyTypeObjectObject"
      maxProperties:
        type: "integer"
        format: "int32"
      minProperties:
        type: "integer"
        format: "int32"
      required:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      properties:
        type: "object"
        additionalProperties:
          $ref: "#/definitions/AnyType"
      propertyGroups:
        type: "array"
        items:
          $ref: "#/definitions/PropertyGroup"
      definitions:
        type: "object"
        additionalProperties:
          $ref: "#/definitions/AnyType"
      type:
        type: "string"
        enum:
        - "String"
        - "Number"
        - "Integer"
        - "Boolean"
        - "Object"
        - "Array"
        - "Null"
        - "Ref"
      additionalProperties:
        type: "object"
  Type:
    type: "object"
    properties:
      typeName:
        type: "string"
  AccessibleProperty:
    type: "object"
    properties:
      name:
        type: "string"
      required:
        type: "boolean"
        default: false
      genericType:
        $ref: "#/definitions/Type"
      accessibleObject:
        $ref: "#/definitions/AccessibleObject"
  FusionResource:
    type: "object"
    properties:
      type:
        type: "string"
        enum:
        - "APPKIT_APP"
        - "APP"
        - "COLLECTION"
        - "INDEX_PIPELINE"
        - "INDEX_STAGE"
        - "QUERY_STAGE"
        - "QUERY_PIPELINE"
        - "INDEX_PROFILE"
        - "QUERY_PROFILE"
        - "BLOB"
        - "PARSER"
        - "DATASOURCE"
        - "TASK"
        - "SCHEDULE"
        - "SEARCH_CLUSTER"
        - "EXPERIMENT"
        - "SPARK_JOB"
        - "GROUP"
        - "TYPE"
        - "RESOURCE"
        - "NULL"
      id:
        type: "string"
      simpleName:
        type: "string"
      canonicalName:
        type: "string"
      uri:
        type: "string"
        format: "uri"
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  AccessibleObject:
    type: "object"
    properties:
      annotations:
        type: "array"
        items:
          $ref: "#/definitions/Annotation"
      declaredAnnotations:
        type: "array"
        items:
          $ref: "#/definitions/Annotation"
      accessible:
        type: "boolean"
        default: false
  AnyType:
    type: "object"
    properties:
      title:
        type: "string"
      description:
        type: "string"
      category:
        type: "string"
      categoryPriority:
        type: "integer"
        format: "int32"
      allowedValues:
        type: "array"
        uniqueItems: true
        items:
          type: "object"
      hints:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      defaultValue:
        type: "object"
      accessibleProperty:
        $ref: "#/definitions/AccessibleProperty"
      oneOf:
        type: "array"
        items:
          $ref: "#/definitions/AnyTypeObjectObject"
      type:
        type: "string"
        enum:
        - "String"
        - "Number"
        - "Integer"
        - "Boolean"
        - "Object"
        - "Array"
        - "Null"
        - "Ref"
  JobActionRequest:
    type: "object"
    properties:
      action:
        type: "string"
        enum:
        - "START"
        - "PAUSE"
        - "ABORT"
      comment:
        type: "string"
  AnyTypeObjectObject:
    type: "object"
    properties:
      title:
        type: "string"
      description:
        type: "string"
      category:
        type: "string"
      categoryPriority:
        type: "integer"
        format: "int32"
      allowedValues:
        type: "array"
        uniqueItems: true
        items:
          type: "object"
      hints:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      defaultValue:
        type: "object"
      accessibleProperty:
        $ref: "#/definitions/AccessibleProperty"
      oneOf:
        type: "array"
        items:
          $ref: "#/definitions/AnyTypeObjectObject"
      type:
        type: "string"
        enum:
        - "String"
        - "Number"
        - "Integer"
        - "Boolean"
        - "Object"
        - "Array"
        - "Null"
        - "Ref"