---
swagger: "2.0"
info:
  version: "4.0.2-SNAPSHOT"
  title: "Fusion Service index-profiles"
basePath: "/api/apollo"
tags:
- name: "index-profiles"
schemes:
- "http"
paths:
  /index/{id}:
    post:
      summary: "Index a document using an index profile"
      description: ""
      operationId: "indexPipelineDocument"
      consumes:
      - "application/vnd.lucidworks-document"
      - "application/vnd.solr-document"
      produces:
      - "application/json; qs=1.0"
      parameters:
      - name: "id"
        in: "path"
        description: "The ID of the index profile to use"
        required: true
        type: "string"
      - name: "simulate"
        in: "query"
        description: "If true, documents are not sent to Solr for indexing; the solr-index\
          \ stage will be skipped"
        required: false
        type: "boolean"
        default: false
      - name: "echo"
        in: "query"
        description: "If true, return the list of documents indexed; otherwise no\
          \ output is returned when the pipeline has finished"
        required: false
        type: "boolean"
        default: true
      - name: "echoMaxCount"
        in: "query"
        description: "The maximum number of documents to list in the output"
        required: false
        type: "integer"
        default: 100
        format: "int32"
      - name: "stats"
        in: "query"
        required: false
        type: "boolean"
        default: false
      - name: "bufferDocsForSolr"
        in: "query"
        required: false
        type: "boolean"
        default: false
      - in: "body"
        name: "body"
        description: "A PipelineDocument or Solr XML document"
        required: false
        schema:
          $ref: "#/definitions/IterablePipelineDocument"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/IndexPipelineStatResponse"
  /index/{id}/debug:
    post:
      summary: "Index a document using an index profile; display debug information"
      description: "This endpoint returns additional information on the state of the\
        \ document after each stage"
      operationId: "debug"
      consumes:
      - "application/vnd.lucidworks-document"
      - "application/json"
      produces:
      - "application/vnd.lucidworks-document"
      - "application/json"
      - "application/vnd.solr-document; qs=0.9"
      parameters:
      - name: "id"
        in: "path"
        description: "The ID of the index profile to use"
        required: true
        type: "string"
      - name: "simulate"
        in: "query"
        description: "If true, documents are not sent to Solr for indexing; the solr-index\
          \ stage will be skipped"
        required: false
        type: "boolean"
        default: false
      - name: "echo"
        in: "query"
        description: "If true, return the list of documents indexed; otherwise no\
          \ output is returned when the pipeline has finished"
        required: false
        type: "boolean"
        default: true
      - name: "echoMaxCount"
        in: "query"
        description: "The maximum number of documents to list in the output"
        required: false
        type: "integer"
        default: 100
        format: "int32"
      - name: "bufferDocsForSolr"
        in: "query"
        description: "If true, documents are buffered before sending to Solr; this\
          \ is an asynchronous mode and may give faster performance when indexing\
          \ a large number of documents"
        required: false
        type: "boolean"
        default: false
      - in: "body"
        name: "body"
        description: "A PipelineDocument or JSON document"
        required: false
        schema:
          $ref: "#/definitions/IterablePipelineDocument"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/IndexPipelineDebugResponse"
definitions:
  IndexPipelineStatResponse:
    type: "object"
    properties:
      docs:
        type: "array"
        items:
          $ref: "#/definitions/PipelineDocument"
      stats:
        type: "object"
        additionalProperties:
          type: "object"
  ContextAndDoc:
    type: "object"
    properties:
      context:
        type: "object"
        additionalProperties:
          type: "object"
      error:
        type: "string"
      doc:
        $ref: "#/definitions/PipelineDocument"
  Command:
    type: "object"
    properties:
      name:
        type: "string"
      params:
        type: "object"
        additionalProperties:
          type: "string"
  InputStream:
    type: "object"
  PipelineField:
    type: "object"
    properties:
      name:
        type: "string"
      value:
        type: "object"
      annotations:
        type: "array"
        items:
          $ref: "#/definitions/Annotation"
      metadata:
        type: "object"
        additionalProperties:
          type: "string"
      annotationsSize:
        type: "integer"
        format: "int32"
      metadataNames:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
  Annotation:
    type: "object"
    properties:
      type:
        type: "string"
      start:
        type: "integer"
        format: "int64"
      end:
        type: "integer"
        format: "int64"
      features:
        type: "object"
        additionalProperties:
          type: "string"
      featureCount:
        type: "integer"
        format: "int32"
  IndexPipelineDebugResponse:
    type: "object"
    properties:
      stages:
        type: "array"
        items:
          $ref: "#/definitions/StageConfig"
      output:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            $ref: "#/definitions/ContextAndDoc"
      outputEncounteredCount:
        type: "integer"
        format: "int64"
  StageConfig:
    type: "object"
    properties:
      type:
        type: "string"
      id:
        type: "string"
      skip:
        type: "boolean"
        default: false
      label:
        type: "string"
      condition:
        type: "string"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
  PipelineDocument:
    type: "object"
    properties:
      id:
        type: "string"
      fields:
        type: "object"
        additionalProperties:
          type: "array"
          items:
            $ref: "#/definitions/PipelineField"
      metadata:
        type: "object"
        additionalProperties:
          type: "string"
      hints:
        type: "object"
        additionalProperties:
          type: "array"
          uniqueItems: true
          items:
            type: "string"
      commands:
        type: "array"
        items:
          $ref: "#/definitions/Command"
      content:
        type: "array"
        items:
          type: "string"
          format: "byte"
      flattenedFields:
        type: "array"
        items:
          $ref: "#/definitions/PipelineField"
      metadataNames:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      allFieldNames:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      reservedFieldNames:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
      fieldNames:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
