---
swagger: "2.0"
info:
  version: "4.0.2-SNAPSHOT"
  title: "Fusion Service introspect"
basePath: "/api/apollo"
tags:
- name: "introspect"
schemes:
- "http"
paths:
  /introspect:
    get:
      operationId: "listServices"
      produces:
      - "application/json"
      parameters:
      - name: "local"
        in: "query"
        required: false
        type: "boolean"
        default: false
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              $ref: "#/definitions/ResourceDescriptor"
          headers: {}
  /introspect/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
  /introspect/{service}:
    get:
      operationId: "getServiceInstance"
      produces:
      - "application/json"
      parameters:
      - name: "service"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ResourceDescriptor"
          headers: {}
definitions:
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  ResourceMethodDescriptor:
    type: "object"
    properties:
      uri:
        type: "string"
      name:
        type: "string"
      verb:
        type: "string"
      pathParams:
        type: "array"
        items:
          $ref: "#/definitions/ParamNameAndClass"
      queryParams:
        type: "array"
        items:
          $ref: "#/definitions/ParamNameAndClass"
      hasEntity:
        type: "boolean"
        default: false
  ParamNameAndClass:
    type: "object"
    properties:
      name:
        type: "string"
      type:
        type: "string"
  ResourceDescriptor:
    type: "object"
    properties:
      name:
        type: "string"
      uri:
        type: "string"
      baseApiUri:
        type: "string"
      methods:
        type: "array"
        items:
          $ref: "#/definitions/ResourceMethodDescriptor"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
