---
swagger: "2.0"
info:
  version: "4.0.2-SNAPSHOT"
  title: "Fusion Service swagger"
basePath: "/api/apollo"
tags:
- name: "swagger"
schemes:
- "http"
paths:
  /swagger:
    get:
      summary: "Get Fusion API spec as JSON"
      description: ""
      operationId: "allJson"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /swagger/multi-json:
    get:
      summary: "Get Fusion per-service API specs as JSON list"
      description: ""
      operationId: "perServiceJson"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /swagger/multi-yaml:
    get:
      summary: "Get Fusion per-service API specs as concatenated YAML blocks"
      description: ""
      operationId: "perServiceYaml"
      produces:
      - "text/yaml"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /swagger/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
  /swagger/yaml:
    get:
      summary: "Get Fusion API spec as YAML"
      description: ""
      operationId: "allYaml"
      produces:
      - "text/yaml"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
definitions:
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
