---
swagger: "2.0"
info:
  version: "4.1.3"
  title: "Fusion Service license"
basePath: "/api/apollo"
tags:
- name: "license"
schemes:
- "http"
paths:
  /license:
    get:
      summary: "Export current Fusion License"
      description: ""
      operationId: "exportLicense"
      produces:
      - "application/octet-stream; qs=0.9"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "string"
              format: "byte"
    put:
      summary: "Replace current Fusion License with new license file"
      description: ""
      operationId: "replaceLicense"
      consumes:
      - "application/octet-stream"
      parameters:
      - in: "body"
        name: "body"
        description: "New License"
        required: false
        schema:
          type: "array"
          items:
            type: "string"
            format: "byte"
      responses:
        default:
          description: "successful operation"
  /license/cache:
    delete:
      summary: "Clears any cached data related to a license, such as to apply a license\
        \ change immediately."
      description: ""
      operationId: "clearCache"
      parameters: []
      responses:
        default:
          description: "successful operation"
  /license/capability/{capability}:
    get:
      summary: "Gets the licensed Capability details"
      description: ""
      operationId: "getCapability"
      produces:
      - "application/json"
      parameters:
      - name: "capability"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "string"
  /license/check:
    get:
      summary: "Check if the license is valid"
      description: ""
      operationId: "checkLicense"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "boolean"
  /license/expiration:
    get:
      summary: "Gets the Expiration Date for the current Fusion License"
      description: ""
      operationId: "getExpirationDate"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
            format: "date-time"
  /license/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
definitions:
  LicenseInfo:
    type: "object"
    properties:
      licensedCapabilities:
        type: "object"
        additionalProperties:
          type: "string"
      expirationDate:
        type: "string"
        format: "date-time"
      isValid:
        type: "boolean"
        default: false
      isInstalled:
        type: "boolean"
        default: false
      validationErrors:
        type: "array"
        items:
          type: "string"
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
