---
swagger: "2.0"
info:
  version: "4.1.3"
  title: "Fusion Service query-pipeline-templates"
basePath: "/api/apollo"
tags:
- name: "query-pipeline-templates"
schemes:
- "http"
paths:
  /templates/query-pipelines:
    get:
      operationId: "getTemplates"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/IterableQueryPipelineDefinition"
          headers: {}
  /templates/query-pipelines/default:
    get:
      operationId: "getSearchDefaultsTemplate"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/QueryPipelineDefinition"
          headers: {}
  /templates/query-pipelines/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
  /templates/query-pipelines/{templateId}:
    get:
      operationId: "getTemplate"
      produces:
      - "application/json"
      parameters:
      - name: "templateId"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/QueryPipelineDefinition"
          headers: {}
definitions:
  PipelineDefinitionFactoryQueryPipelineDefinition:
    type: "object"
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  QueryPipelineDefinition:
    type: "object"
    properties:
      id:
        type: "string"
      stageConfigurations:
        type: "array"
        items:
          $ref: "#/definitions/StageConfig"
      properties:
        type: "object"
        additionalProperties:
          type: "string"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      factory:
        $ref: "#/definitions/PipelineDefinitionFactoryQueryPipelineDefinition"
      unsafe:
        type: "boolean"
        default: false
      hidden:
        type: "boolean"
        default: false
  StageConfig:
    type: "object"
    properties:
      type:
        type: "string"
      id:
        type: "string"
      skip:
        type: "boolean"
        default: false
      label:
        type: "string"
      condition:
        type: "string"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
