---
swagger: "2.0"
info:
  version: "4.1.3"
  title: "Fusion Service links"
basePath: "/api/apollo"
tags:
- name: "links"
schemes:
- "http"
paths:
  /links:
    get:
      summary: "Get all links, or links matching the given criteria"
      description: "For the request body, an asterisk (*) can be used in place of\
        \ an ID to indicate a wildcard"
      operationId: "listLinks"
      produces:
      - "application/json"
      parameters:
      - name: "subject"
        in: "query"
        description: "Return only links with a matching subject"
        required: false
        type: "string"
        default: "*"
      - name: "object"
        in: "query"
        description: "Return only links with a matching object"
        required: false
        type: "string"
        default: "*"
      - name: "linkType"
        in: "query"
        description: "Return only links with a matching type"
        required: false
        type: "string"
        default: "*"
      - name: "transitive"
        in: "query"
        description: "Return transitive links"
        required: false
        type: "boolean"
        default: false
      - name: "bypassCache"
        in: "query"
        description: "Bypass the cache and retrieve directly from storage"
        required: false
        type: "boolean"
        default: false
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Link"
    put:
      summary: "Link two objects together with a link type"
      description: ""
      operationId: "putLink"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "JSON-formatted link definition that specifies the subject, object,\
          \ and linkType"
        required: false
        schema:
          $ref: "#/definitions/Link"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Link"
    delete:
      summary: "Delete links matching the provided criteria"
      description: "For the request body, an asterisk (*) can be used in place of\
        \ an ID to indicate a wildcard"
      operationId: "deleteLink"
      parameters:
      - name: "subject"
        in: "query"
        description: "Delete only links with a matching subject"
        required: false
        type: "string"
      - name: "object"
        in: "query"
        description: "Delete only links with a matching object"
        required: false
        type: "string"
      - name: "linkType"
        in: "query"
        description: "Delete only links with a matching type"
        required: false
        type: "string"
      responses:
        default:
          description: "successful operation"
  /links/contexts:
    get:
      summary: "Get all Fusion app contexts from list of passed for each of resources\
        \ passed"
      description: "Don't pass contexts if you want to evaluate against all existing\
        \ Fusion apps"
      operationId: "findContexts"
      produces:
      - "application/json"
      parameters:
      - name: "contexts"
        in: "query"
        description: "List of Fusion apps to check against"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      - name: "resources"
        in: "query"
        description: "List of Fusion apps to check against"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      - name: "bypassCache"
        in: "query"
        description: "Bypass the cache and retrieve directly from storage"
        required: false
        type: "boolean"
        default: false
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "array"
              uniqueItems: true
              items:
                $ref: "#/definitions/FusionResource"
  /links/directed:
    get:
      summary: "Return outgoing links for the given resource"
      description: "Exclusive means objects used by the given resource and not used\
        \ by other resources."
      operationId: "getDirectedLinks"
      produces:
      - "application/json"
      parameters:
      - name: "resource"
        in: "query"
        description: "Resource to get exclusive links for"
        required: false
        type: "string"
      - name: "exclusive"
        in: "query"
        required: false
        type: "boolean"
        default: false
      - name: "bypassCache"
        in: "query"
        description: "Bypass the cache and retrieve directly from storage"
        required: false
        type: "boolean"
        default: false
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Link"
  /links/status:
    get:
      summary: "Get the status of the service"
      description: ""
      operationId: "getStatus"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
definitions:
  FusionResource:
    type: "object"
    properties:
      type:
        type: "string"
        enum:
        - "APPKIT_APP"
        - "APP"
        - "COLLECTION"
        - "INDEX_PIPELINE"
        - "INDEX_STAGE"
        - "QUERY_STAGE"
        - "QUERY_PIPELINE"
        - "INDEX_PROFILE"
        - "QUERY_PROFILE"
        - "BLOB"
        - "PARSER"
        - "DATASOURCE"
        - "TASK"
        - "SCHEDULE"
        - "SEARCH_CLUSTER"
        - "EXPERIMENT"
        - "SPARK_JOB"
        - "GROUP"
        - "TYPE"
        - "RESOURCE"
        - "NULL"
      id:
        type: "string"
      simpleName:
        type: "string"
      canonicalName:
        type: "string"
      uri:
        type: "string"
        format: "uri"
  ServiceStatus:
    type: "object"
    properties:
      node:
        type: "string"
      status:
        type: "string"
        enum:
        - "starting"
        - "ok"
        - "warning"
        - "error"
        - "shutdown"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/StatusMessage"
  Link:
    type: "object"
    properties:
      subject:
        $ref: "#/definitions/FusionResource"
      object:
        $ref: "#/definitions/FusionResource"
      linkType:
        type: "string"
        enum:
        - "DependsOn"
        - "Supports"
        - "IsPartOf"
        - "HasPart"
        - "RelatesTo"
        - "InContextOf"
        - "HasContext"
        - "Self"
      originator:
        type: "string"
      id:
        type: "string"
      additionalProperties:
        type: "object"
        additionalProperties:
          type: "object"
  StatusMessage:
    type: "object"
    properties:
      message:
        type: "string"
      date:
        type: "string"
        format: "date-time"
